### ISSUE TITLE
Clickable links

### ISSUE THREAD

**Issue by piaaaac** [darenju/react-flip-page#13]
Would it possible to make a link clickable on a flippable page?

**Comment by darenju** [comment]
This is apparently a `z-index` problem. I'm working on that.

**Comment by darenju** [comment]
This should be fixed.

Can you try on your side please?

Here is a quick snippet:

```
<FlipPage>
  <div>
    <img src="http://unsplash.it/320/320/?image=32" />

    <h2>Google</h2>
    <a href="http://www.google.com" target="_blank">Google</a>
  </div>
  <div>
    <h2>YouTube</h2>
    <a href="http://www.youtube.com" target="_blank">YouTube</a>

    <img src="http://unsplash.it/320/320/?image=16" />
  </div>
</FlipPage>
```

**Comment by piaaaac** [comment]
Actually it's still not clickable. this is the content of the pages:

```
const Top5Headline = ({ newsData, i }) => {
  const nd = newsData
  const pillarClass = 'pillar-' + nd.pillar
  return (
    <div className="container-fluid">

      <div className="row">
        <div className="col-sm-12">
          <h1 className="section-title">In the News</h1>
        </div>
      </div>

      <div className="row">
        <div className="col-sm-12 item">
          <p className={'headline-top5 pillar-' + nd.pillar}>{nd.title}</p>
          <p className="source-top5-l1">Read it on</p>
          <p className="source-top5-l2">
            <a href={nd.url} target="_blank">{nd.publication}</a>
          </p>
        </div>
      </div>

    </div>
  )
}
```

**Comment by piaaaac** [comment]
What I'm doing now as a workaround is to place the clickable content outside the component, on top of it absolutely positioned. Downside of this solution is obviously that this content is not subject to the flip animation.

**Comment by darenju** [comment]
Do you have a test page so I can take a look maybe?

**Comment by piaaaac** [comment]
Actually I found that isolating the component it works, so it must be some other problem on my side. Thanks a lot !
